pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clona el repositorio desde GitHub
                git url: 'https://github.com/carloscoronaba/Mensajeria', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                // Aquí puedes agregar pasos de construcción si es necesario
                echo 'Build successful!'
            }
        }
        stage('Test') {
            steps {
                // Aquí puedes agregar pasos de pruebas si es necesario
                echo 'Tests passed!'
            }
        }
    }

    post {
        success {
            // Acciones a realizar en caso de éxito
            echo 'Pipeline succeeded!'
        }
        failure {
            // Acciones a realizar en caso de fallo
            echo 'Pipeline failed!'
        }
    }
}
